In [11]:
import numpy as np


## Task 1

In [12]:
array= np.random.randint(1,20,size=15)

In [23]:
a

array([13, 13, 14,  4, 19,  9,  9,  2,  2, 16, 13, 11, 11, 17, 15])

In [24]:
standard_dev=np.std(a)

In [25]:
standard_dev

5.035871324805669

## Task 2

In [20]:

matrix = np.random.randint(1,100,(5, 5))
row_min = np.min(matrix, axis=1)
row_max = np.max(matrix, axis=1)


column_min = np.min(matrix, axis=0)
column_max = np.max(matrix, axis=0)

print("Random 5x5 Matrix:\n", matrix)
print("Minimum values along each row:", row_min)
print("Maximum values along each row:", row_max)
print("Minimum values along each column:", column_min)
print("Maximum values along each column:", column_max)


Random 5x5 Matrix:
 [[26 98 42  4 30]
 [21 35 85 97 98]
 [98 83 10 63 59]
 [27  9 55 12 57]
 [67  7 61 86 56]]
Minimum values along each row: [ 4 21 10  9  7]
Maximum values along each row: [98 98 98 57 86]
Minimum values along each column: [21  7 10  4 30]
Maximum values along each column: [98 98 85 97 98]


## Task 3

In [22]:
import numpy as np

def cosine_similarity(vector_a, vector_b):
    unit_vector_a = vector_a / np.linalg.norm(vector_a)
    unit_vector_b = vector_b / np.linalg.norm(vector_b)
    similarity = np.dot(unit_vector_a, unit_vector_b)
    return similarity

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

similarity = np.cos(cosine_similarity(vector_a, vector_b))
print("Cosine Similarity:", similarity)


Cosine Similarity: 0.5614727371106946
